// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_001;

#nullable disable

namespace Task_001.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20260513092109_SeedUsersAndRoles")]
    partial class SeedUsersAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseDepartment", b =>
                {
                    b.Property<int>("CourseDepartmentsDeptId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentCoursesCrsId")
                        .HasColumnType("int");

                    b.HasKey("CourseDepartmentsDeptId", "DepartmentCoursesCrsId");

                    b.HasIndex("DepartmentCoursesCrsId");

                    b.ToTable("CourseDepartment");
                });

            modelBuilder.Entity("CourseInstructor", b =>
                {
                    b.Property<int>("CourseInstructorsInsId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorCoursesCrsId")
                        .HasColumnType("int");

                    b.HasKey("CourseInstructorsInsId", "InstructorCoursesCrsId");

                    b.HasIndex("InstructorCoursesCrsId");

                    b.ToTable("CourseInstructor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "u1",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u9",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u10",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u11",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "u13",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Task_001.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u1",
                            Email = "aly@iti.gov",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALY@ITI.GOV",
                            NormalizedUserName = "ALY@ITI.GOV",
                            PasswordHash = "AQAAAAIAAYagAAAAEAgm9vKdxI5Pe9ZxW8psE/NeWl3ApJABFqRiI5DVsWf9bxcp2/qDGzektXxaep7vrQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u1",
                            StudentId = 1,
                            TwoFactorEnabled = false,
                            UserName = "aly@iti.gov"
                        },
                        new
                        {
                            Id = "u2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u2",
                            Email = "sara@iti.gov",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@ITI.GOV",
                            NormalizedUserName = "SARA@ITI.GOV",
                            PasswordHash = "AQAAAAIAAYagAAAAEDKX8wZgqbu2M8XB0kDqfRMvQpOj1B2XWzk3oljsv1soKtfIMxQK4b2nDuLlap3KDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u2",
                            StudentId = 2,
                            TwoFactorEnabled = false,
                            UserName = "sara@iti.gov"
                        },
                        new
                        {
                            Id = "u3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u3",
                            Email = "ahmed@iti.gov",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMED@ITI.GOV",
                            NormalizedUserName = "AHMED@ITI.GOV",
                            PasswordHash = "AQAAAAIAAYagAAAAENHAHzMxcyGsr1nYaKN70vdRdPY3tMiCNMMpKiiPW/28eO2vMoeHjW7UDFmYYfIsww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u3",
                            StudentId = 3,
                            TwoFactorEnabled = false,
                            UserName = "ahmed@iti.gov"
                        },
                        new
                        {
                            Id = "u8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u8",
                            Email = "khaled@iti.gov",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KHALED@ITI.GOV",
                            NormalizedUserName = "KHALED@ITI.GOV",
                            PasswordHash = "AQAAAAIAAYagAAAAECpzYQybWfeWinat8NtDchhY7UzEw/MdHDrDMZW4DjABr6WMQqvhuaPoEQ61jBivJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u8",
                            StudentId = 8,
                            TwoFactorEnabled = false,
                            UserName = "khaled@iti.gov"
                        },
                        new
                        {
                            Id = "u9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u9",
                            Email = "metwally@iti.gov",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "METWALLY@ITI.GOV",
                            NormalizedUserName = "METWALLY@ITI.GOV",
                            PasswordHash = "AQAAAAIAAYagAAAAEC8/UKja4i8wxehs9WfSuz3AqsRPTewzScWsJyFENqEoMCr2eOWSC3g5ptEIuBiN5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u9",
                            StudentId = 9,
                            TwoFactorEnabled = false,
                            UserName = "metwally@iti.gov"
                        },
                        new
                        {
                            Id = "u10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u10",
                            Email = "mt@m.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MT@M.COM",
                            NormalizedUserName = "MT@M.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO/al6JELwywL5gSL7YmzdQzEbnRLoSK13Ex5k/vJfq8GAKs+Oj7Gefrk1sD5SoARQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u10",
                            StudentId = 10,
                            TwoFactorEnabled = false,
                            UserName = "mt@m.com"
                        },
                        new
                        {
                            Id = "u11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u11",
                            Email = "b@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "B@MAIL.COM",
                            NormalizedUserName = "B@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGJpO69yYNQPWKxDkfuU+5jYyNopK15OMDRQrc0ZUUWQVKfh7+Y6KSPmY0GSSX3dog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u11",
                            StudentId = 11,
                            TwoFactorEnabled = false,
                            UserName = "b@mail.com"
                        },
                        new
                        {
                            Id = "u13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "u13",
                            Email = "A@B.C",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "A@B.C",
                            NormalizedUserName = "A@B.C",
                            PasswordHash = "AQAAAAIAAYagAAAAEDNvC6qhVVMA8ux0AD+dQ6UFUW43fCXvDD2y3aviRd6oIW0/HNMinPoG6diS/w7rfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "u13",
                            StudentId = 13,
                            TwoFactorEnabled = false,
                            UserName = "A@B.C"
                        });
                });

            modelBuilder.Entity("Task_001.Course", b =>
                {
                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CrsId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Task_001.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("MgrId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DeptId");

                    b.HasIndex("MgrId")
                        .IsUnique()
                        .HasFilter("[MgrId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 100,
                            Capacity = 50,
                            Name = ".net",
                            Status = true
                        },
                        new
                        {
                            DeptId = 200,
                            Capacity = 30,
                            Name = "pd",
                            Status = true
                        },
                        new
                        {
                            DeptId = 300,
                            Capacity = 25,
                            Name = "os",
                            Status = true
                        });
                });

            modelBuilder.Entity("Task_001.Instructor", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int");

                    b.Property<int?>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsId");

                    b.HasIndex("DeptNo");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Task_001.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeptNo");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Task_001.StudentCourse", b =>
                {
                    b.Property<int>("StdId")
                        .HasColumnType("int");

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<int?>("Degree")
                        .HasColumnType("int");

                    b.HasKey("StdId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("CourseDepartment", b =>
                {
                    b.HasOne("Task_001.Department", null)
                        .WithMany()
                        .HasForeignKey("CourseDepartmentsDeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_001.Course", null)
                        .WithMany()
                        .HasForeignKey("DepartmentCoursesCrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseInstructor", b =>
                {
                    b.HasOne("Task_001.Instructor", null)
                        .WithMany()
                        .HasForeignKey("CourseInstructorsInsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_001.Course", null)
                        .WithMany()
                        .HasForeignKey("InstructorCoursesCrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Task_001.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Task_001.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_001.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Task_001.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Task_001.ApplicationUser", b =>
                {
                    b.HasOne("Task_001.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Task_001.Department", b =>
                {
                    b.HasOne("Task_001.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("Task_001.Department", "MgrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Task_001.Instructor", b =>
                {
                    b.HasOne("Task_001.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Task_001.Student", b =>
                {
                    b.HasOne("Task_001.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptNo");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Task_001.StudentCourse", b =>
                {
                    b.HasOne("Task_001.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_001.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Task_001.Course", b =>
                {
                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("Task_001.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Task_001.Instructor", b =>
                {
                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("Task_001.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
