// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Task_003.Models;

public partial class Course
{
    public int CrsId { get; set; }

    public string Name { get; set; }

    public int Duration { get; set; }

    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    public virtual ICollection<Department> CourseDepartmentsDepts { get; set; } = new List<Department>();

    public virtual ICollection<Instructor> CourseInstructorsIns { get; set; } = new List<Instructor>();
}