// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Task_003.Models;

public partial class Department
{
    public int DeptId { get; set; }

    public string Name { get; set; }

    public int Capacity { get; set; }

    public int MgrId { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual Instructor Mgr { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<Course> DepartmentCoursesCrs { get; set; } = new List<Course>();
}