// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Task_003.Models;

public partial class Instructor
{
    public int InsId { get; set; }

    public string Name { get; set; }

    public int? DeptNo { get; set; }

    public virtual Department Department { get; set; }

    public virtual Department DeptNoNavigation { get; set; }

    public virtual ICollection<Course> InstructorCoursesCrs { get; set; } = new List<Course>();
}