// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Task_003.Models;

public partial class SchoolContext : DbContext
{
    public SchoolContext()
    {
    }

    public SchoolContext(DbContextOptions<SchoolContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentCourse> StudentCourses { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=localhost\\SQLEXPRESS;Initial Catalog=efcorev1;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {


        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CrsId);

            entity.Property(e => e.CrsId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DeptId);

            entity.HasIndex(e => e.MgrId, "IX_Departments_MgrId").IsUnique();

            entity.Property(e => e.DeptId).ValueGeneratedNever();

            entity.HasOne(d => d.Mgr).WithOne(p => p.Department)
                .HasForeignKey<Department>(d => d.MgrId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasMany(d => d.DepartmentCoursesCrs).WithMany(p => p.CourseDepartmentsDepts)
                .UsingEntity<Dictionary<string, object>>(
                    "CourseDepartment",
                    r => r.HasOne<Course>().WithMany().HasForeignKey("DepartmentCoursesCrsId"),
                    l => l.HasOne<Department>().WithMany().HasForeignKey("CourseDepartmentsDeptId"),
                    j =>
                    {
                        j.HasKey("CourseDepartmentsDeptId", "DepartmentCoursesCrsId");
                        j.ToTable("CourseDepartment");
                        j.HasIndex(new[] { "DepartmentCoursesCrsId" }, "IX_CourseDepartment_DepartmentCoursesCrsId");
                    });
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.InsId);

            entity.HasIndex(e => e.DeptNo, "IX_Instructors_DeptNo");

            entity.Property(e => e.InsId).ValueGeneratedNever();

            entity.HasOne(d => d.DeptNoNavigation).WithMany(p => p.Instructors).HasForeignKey(d => d.DeptNo);

            entity.HasMany(d => d.InstructorCoursesCrs).WithMany(p => p.CourseInstructorsIns)
                .UsingEntity<Dictionary<string, object>>(
                    "CourseInstructor",
                    r => r.HasOne<Course>().WithMany().HasForeignKey("InstructorCoursesCrsId"),
                    l => l.HasOne<Instructor>().WithMany().HasForeignKey("CourseInstructorsInsId"),
                    j =>
                    {
                        j.HasKey("CourseInstructorsInsId", "InstructorCoursesCrsId");
                        j.ToTable("CourseInstructor");
                        j.HasIndex(new[] { "InstructorCoursesCrsId" }, "IX_CourseInstructor_InstructorCoursesCrsId");
                    });
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasIndex(e => e.DeptNo, "IX_Students_DeptNo");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.DeptNoNavigation).WithMany(p => p.Students).HasForeignKey(d => d.DeptNo);
        });

        modelBuilder.Entity<StudentCourse>(entity =>
        {
            entity.HasKey(e => new { e.StdId, e.CrsId });

            entity.HasIndex(e => e.CrsId, "IX_StudentCourses_CrsId");

            entity.HasOne(d => d.Crs).WithMany(p => p.StudentCourses).HasForeignKey(d => d.CrsId);

            entity.HasOne(d => d.Std).WithMany(p => p.StudentCourses).HasForeignKey(d => d.StdId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}